export const BRAND = {
  name: "Open Nest",
  tagline: "Your Trusted Tech Store in the UAE",
  phone: "+971 4 123 4567",
  email: "info@opennest.ae",
  address: "Dubai, UAE",
  whatsapp: "+971501234567",
  currency: "AED",
  freeDeliveryThreshold: 500,
  primaryColor: "#FF6B2B",
  secondaryColor: "#0A2540",
  logo: "/logo.svg",
  socials: {
    instagram: "https://instagram.com/opennest.ae",
    facebook: "https://facebook.com/opennest.ae",
    twitter: "https://twitter.com/opennest_ae",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Products", href: "/products" },
    { label: "Categories", href: "/categories" },
    { label: "Deals", href: "/deals" },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  categories: [
    { label: "Processors (CPU)", slug: "cpu", icon: "cpu" },
    { label: "Graphics Cards (GPU)", slug: "gpu", icon: "gpu" },
    { label: "Laptops", slug: "laptops", icon: "laptop" },
    { label: "Monitors", slug: "monitors", icon: "monitor" },
    { label: "Storage", slug: "storage", icon: "storage" },
    { label: "Networking", slug: "networking", icon: "networking" },
    { label: "Peripherals", slug: "peripherals", icon: "peripherals" },
    { label: "Gaming", slug: "gaming", icon: "gaming" },
  ],
};
